name: Create Binary

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: ['windows-latest','macos-latest']

    steps:
    - uses: actions/checkout@v2
    - name: Customize git
      run: |
        git submodule update --init --recursive
        git fetch --prune --unshallow
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install installer dependencies [Python]
      run: |
        pip install wheel dqrobotics pillow pyinstaller pyserial PyQt6
    - name: Run pyinstaller
      run: |
        pyinstaller installer.spec
    - name: Upload Artifact (Windows)
      if: matrix.os == 'windows-latest'
      with:
        name: UMIRobotGUI_Windows_am64
        path: dist/UMIRobotGUI.exe
        retention-days: 1
    - name: Upload Artifact (MacOS-Intel)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v3
      with:
        name: UMIRobotGUI_MacOS_amd64
        path: dist/UMIRobotGUI.app
        retention-days: 1
